-- =========================================================================
--   ASCL (Aminisa Sport Club League) - SUPABASE DATABASE TABLE SETUP DDL
-- =========================================================================
-- Run this SQL script in your Supabase SQL Editor to create the necessary 
-- table and enable permissions for client-side registration synchronization.

-- 1. Create the Player Registrations table
CREATE TABLE IF NOT EXISTS public.player_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uniquePlayerId" TEXT NOT NULL UNIQUE,
    "registrationDate" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    nickname TEXT,
    dob TEXT NOT NULL,
    gender TEXT NOT NULL,
    phone TEXT,
    whatsapp TEXT NOT NULL,
    email TEXT NOT NULL,
    "residentialArea" TEXT NOT NULL,
    "experienceYears" INTEGER,
    "preferredCueHand" TEXT NOT NULL,
    "previousTournament" TEXT,
    "skillLevel" TEXT NOT NULL,
    "emergencyName" TEXT,
    "emergencyRelationship" TEXT,
    "emergencyPhone" TEXT,
    "passportPhotoUri" TEXT,
    "paymentProofUri" TEXT,
    "passportData" TEXT, -- Base64 storage for web portal files
    "receiptData" TEXT,  -- Base64 storage for web portal files
    status TEXT NOT NULL DEFAULT 'Pending',
    "referralCode" TEXT,
    "hashValue" BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS) on the table
ALTER TABLE public.player_registrations ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies to allow anonymous reads and writes
-- Allow any user (anon key) to INSERT new applications
CREATE POLICY "Allow anonymous player registrations" 
    ON public.player_registrations 
    FOR INSERT 
    WITH CHECK (true);

-- Allow any user (anon key) to SELECT (view rosters/registrations)
CREATE POLICY "Allow anonymous reading of registrations" 
    ON public.player_registrations 
    FOR SELECT 
    USING (true);

-- Allow any user (anon key) to UPDATE registrations (admin approvals / status updates)
CREATE POLICY "Allow anonymous status updates" 
    ON public.player_registrations 
    FOR UPDATE 
    USING (true)
    WITH CHECK (true);
